---
plugin:
  name: ''
  description: ''
  image: ''
  imagePullPolicy: IfNotPresent
  replicas: 2
  port: 9443
  securityContext:
    enabled: true
  podSecurityContext:
    enabled: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
  basePath: /
  certificateSecretName: ''
  serviceAccount:
    create: true
    annotations: {}
    name: ''
  patcherServiceAccount:
    create: true
    annotations: {}
    name: ''
  jobs:
    patchConsoles:
      enabled: true
      image: 'registry.redhat.io/openshift4/ose-tools-rhel8@sha256:9d826cd5665e88c2f9676e5c1b532eec7a7ad5a679788696a74e08ac82d9f918'
      podSecurityContext:
        enabled: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containerSecurityContext:
        enabled: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
      resources:
        requests:
          cpu: 10m
          memory: 50Mi
